---

- name: Setup cron service
  cron:
    name: 'nextcloud Background Jobs'
    minute: "{{ nextcloud_cron_minute }}"
    user: "{{ nextcloud_user }}"
    job: '/usr/bin/php -f {{ nextcloud_deploy_path }}/nextcloud/cron.php'
    cron_file: 'nextcloud'

- name: Setup logrotate for nextcloud
  template:
    src: etc/logrotate.d/nextcloud.j2
    dest: /etc/logrotate.d/nextcloud
    owner: root
    group: root
    mode: 0644

- name: Check if nextcloud is already configured
  stat:
    path: "{{ nextcloud_deploy_path }}/nextcloud/config/config.php"
  register: nextcloud_config_stat

# If no config is available create the autoconfig
- name: Create autoconfig
  template:
    src: nextcloud/autoconfig.php.j2
    dest: "{{ nextcloud_deploy_path }}/nextcloud/config/autoconfig.php"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 0640
  when: nextcloud_config_stat.stat.exists ==  False

# If the config is available update it
- include: rebuild_config.yml
  when: nextcloud_config_stat.stat.exists ==  True
