---

- name: Create group
  group:
    name: "{{ nextcloud_group }}"
    system: yes
    state: present

- name: Create user
  user:
    name: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    home: "{{ nextcloud_home }}"
    shell: /bin/sh
    comment: "nextcloud"
    system: yes
    state: present

- name: Install Required packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - memcached

- include: deploy.yml

- include: postgresql.yml
  when: nextcloud_db_type == 'postgresql'

- include: mariadb.yml
  when: nextcloud_db_type == 'mariadb'

- include: config.yml
- include: nginx.yml
